services:
  tomcat:
    image: tomcat:latest
    container_name: app-server
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    restart: unless-stopped
  monitor:
    image: monitor:latest
    container_name: monitor
    build:
      context: ./monitor
      dockerfile: dockerfile
    volumes:
      - ./logs:/logs
    depends_on:
      - tomcat
    restart: unless-stopped
  db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    environment: 
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
    ports:
      - 1521:1521
    volumes:
      - ./logs:/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s


