services:
  tomcat:
    image: tomcat:latest
    container_name: app-server
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/conf:/usr/local/tomcat/conf
      - ./certs/generated:/certs
    restart: unless-stopped
  monitor:
    image: monitor:latest
    container_name: monitor
    build:
      context: ./monitor
      dockerfile: dockerfile
    volumes:
      - ./logs:/logs
      - ./certs/generated:/certs
    depends_on:
      - tomcat
    restart: unless-stopped
  db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
    ports:
      - 1521:1521
    volumes:
      - ./logs:/logs
      - ./sql:/sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
  loader:
    image: loader:latest
    container_name: loader
    build:
      context: ./loader
      dockerfile: dockerfile
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
      DB_HOST: db
      DB_PORT: 1521
      DB_SERVICE: FREEPDB1
    volumes:
      - ./logs:/logs
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
