CREATE TABLE METRICS (
    TIME_STAMP TIMESTAMP,
    RAM_PCT    NUMBER(5, 2),
    RAM_USED   NUMBER(7, 2),
    RAM_TOTAL  NUMBER(7, 2),
    DISK_PCT   NUMBER(5, 2),
    CPU_PCT    NUMBER(5, 2)
);

CREATE TABLE STATUS (
    TIME_STAMP  TIMESTAMP,
    HTTP_STATUS NUMBER(5, 2),
    MTLS_NO_CERT NUMBER(5, 2),
    MTLS_CERT NUMBER(5, 2) 
);
EXIT;