LOAD DATA
INFILE '/logs/health-2026-06-14.log'
APPEND
INTO TABLE METRICS
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
  TIME_STAMP TIMESTAMP "YYYY-MM-DD HH24:MI:SS",
  RAM_PCT,
  RAM_USED,
  RAM_TOTAL,
  DISK_PCT,
  CPU_PCT
)