LOAD DATA
INFILE '/logs/service-2026-06-14.log'
APPEND
INTO TABLE STATUS
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
    TIME_STAMP TIMESTAMP "YYYY-MM-DD HH24:MI:SS",
    HTTP_STATUS,
    MTLS_NO_CERT NUMBER,
    MTLS_CERT NUMBER

)